---
- name: Install Node
  hosts: all
  become: true

  vars:
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Install EPEL repo.
      ansible.builtin.dnf: name=epel-release state=present
    - name: Import Remi GPG Key.
      ansible.builtin.rpm_key:
        key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
        state: present
    - name: Install Remi Repo
      ansible.builtin.dnf:
        name: "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
        state: present